### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by palant** [EtherDream/WebScrypt#1]
Thank you for creating this top notch scrypt implementation, in my tests it performs considerably better than scrypt-async on all browsers and devices. Problem is, this repository doesn't contain any license information which prevents me from using your library. Assuming that you want the library to be used in other projects, could you add a license file?

**Comment by EtherDream** [comment]
ok, added. MIT. (this is just an experimental version, I will add the WebAssembly later, and try WebGL2 pbkdf)

**Comment by palant** [comment]
Thanks a lot!
